name: java ci

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Show java version
        run: java -version
      
      - name: show Project Structure
        run: ls -R
            
      - name: Compile Java Project
        run: ./scripts/build.sh

      - name: Show compiled files
        run: find . -name "*.class"

      


